export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"
export PATH="/home/igor/.cargo/bin:$PATH"

export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="ghostty"
export BROWSER="firefox"
export READER="zathura"
export WM="Hyprland"
export PAGER="less"
export LESSFILE="-"
export COLORTERM="truecolor"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"
export HISTFILE="$XDG_STATE_HOME"/zsh
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export SC_DOC_DIR="$HOME/sc"

export SAPF_HISTORY="$HOME/code/sapf/sapf-history.txt"
export SAPF_LOG="$HOME/code/sapf/sapf-log.txt"
export SAPF_PRELUDE="$HOME/code/sapf/sapf-prelude.txt"
export SAPF_EXAMPLES="$HOME/code/sapf/sapf-examples.txt"
export SAPF_README="$HOME/code/sapf/README.txt"
export SAPF_RECORDINGS="$HOME/code/sapf/recordings"
export SAPF_SPECTROGRAMS="$HOME/code/sapf/spectrograms"
